name: ttl_app_code
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.3.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  connectivity_plus: ^3.0.6
  http: ^0.13.6
  shared_preferences: ^2.1.0

  cupertino_icons: ^1.0.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.0.1
  mockito: ^5.0.0
  flutter_lints: ^2.0.1

flutter:
 uses-material-design: true

# flutter_launcher_icons:
# android: "launcher_icon"
# ios: true
# image_path: "assets/icon/icon.png"
# min_sdk_android: 33 # android min sdk min:16, default 21
# web:
#   generate: true
#   image_path: "path/to/image.png"
#   background_color: "#hexcode"
#   theme_color: "#hexcode"
# windows:
#   generate: true
#   image_path: "path/to/image.png"
#   icon_size: 48 # min:48, max:256, default: 48
# macos:
#   generate: true
#   image_path: "path/to/image.png"